plugins {
    id 'java'; id 'org.springframework.boot' version '4.1.1'; id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'; id 'org.sonarqube' version '7.5.0.8588'
}
group = 'com.pragma.powerup'; version = '0.0.1-SNAPSHOT'
java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }
repositories { mavenCentral() }
dependencies {
    implementation 'org.mapstruct:mapstruct:1.6.3'
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
}
tasks.withType(JavaCompile).configureEach { options.compilerArgs += ['-parameters']; options.encoding = 'UTF-8' }
tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperty 'JWT_SECRET', '0123456789abcdef0123456789abcdef'
    finalizedBy jacocoTestReport
}
jacocoTestReport { dependsOn test; classDirectories.setFrom(coverageClasses()); reports { xml.required = true; html.required = true } }
jacocoTestCoverageVerification { dependsOn test; classDirectories.setFrom(coverageClasses()); violationRules { rule { limit { counter = 'LINE'; value = 'COVEREDRATIO'; minimum = 0.82 } } } }
check.dependsOn jacocoTestCoverageVerification
def coverageClasses() { sourceSets.main.output.asFileTree.matching { exclude '**/*Application.class', '**/configuration/**', '**/dto/**', '**/model/**', '**/entity/**', '**/mapper/**', '**/exception/**' } }
sonar { properties { property 'sonar.projectKey', 'ms-foodcourt-users'; property 'sonar.projectName', 'ms-foodcourt-users'; property 'sonar.coverage.jacoco.xmlReportPaths', layout.buildDirectory.file('reports/jacoco/test/jacocoTestReport.xml').get().asFile } }
